analyzer:
#   exclude:
#     - path/to/excluded/files/**

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
    - library_prefixes
    - library_names
    - unnecessary_brace_in_string_interps
    - always_declare_return_types
    - always_specify_types
    - camel_case_types
    - file_names
    - no_duplicate_case_values
    - curly_braces_in_flow_control_structures